###
GET http://localhost:8081/iiko/testOrder

###
GET http://localhost:8081/iiko/getStatus
Content-Type: application/json

{"id": "021e1ee4-0715-4d9b-b352-e32eeae4f155"}

<> 2024-06-08T084832.404.json

###
POST http://localhost:8081/iiko/createOrder
Content-Type: application/json

{
  "items": [
    {
      "itemId": "d97c066c-0a83-49c8-a79b-cf6ec9a4d366",
      "itemNumber": 0
    }
  ],
  "id": 0,
  "comment": "Тестовый заказ, не делать!!!",
  "time": "2024-06-20 23:59:59.999"
}